main.exe: UF1288_LopezSegadoPedroAntonio_EJ2.o servicio.o
	gcc -o UF1288_LopezSegadoPedroAntonio_EJ2.exe UF1288_LopezSegadoPedroAntonio_EJ2.o servicio.o

main.o: UF1288_LopezSegadoPedroAntonio_EJ2.c servicio.h
	gcc -c UF1288_LopezSegadoPedroAntonio_EJ2.c 

funciones.o: servicio.c servicio.h
	gcc -c servicio.c